### ISSUE TITLE
Diagram

### ISSUE THREAD

**Issue by Dihdim** [dimitra216/CSC496-Team-Cloud-Project-DA#1]
![Screen Shot Ass#2](https://user-images.githubusercontent.com/47375286/76051451-d3890100-5f38-11ea-98d4-fc29bcd86339.PNG)

**Comment by ddeliopoulos** [comment]
Good morning,

I went ahead and figured out how to upload that image on the documentation.
I think it looks great and we can continue adding to it as we go. I doubt
Dr. Ngo has seen the repository yet and he said in class that the
Documentation that we upload should be a blueprint that he can read so he
is able to help us by asking the right questions.

Thanks,
Dimitra
